version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"           # dónde está el package.json
    schedule:
      interval: "weekly"     # también puede ser: daily, monthly
    open-pull-requests-limit: 5
    labels:
      - "security"
      - "dependencies"