server {
  listen 80;

  # Sirve los archivos estáticos normalmente
  location / {
    root /usr/share/nginx/html;
    index index.html;
  }

  # Redirige /api/ hacia el servicio "api" en la red interna
  location /api/ {
    proxy_pass http://api:80/;
    proxy_set_header Host $host;
  }
}